{{ $fullname := include "loki-docs.fullname" . }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullname }}-trigger-secret
  labels:
    {{- include "loki-docs.labels" . | nindent 4 }}
spec:
  encryptedData:
    WebHookSecretKey: {{ .Values.source.triggerSecret }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: loki-docs
        app.kubernetes.io/managed-by: SealedSecrets
        app.kubernetes.io/name: loki-docs
        helm.sh/chart: loki-docs-1.0.0
      name: loki-docs-trigger-secret
      namespace: kes-cluster-management

