{{ $fullname := include "loki-docs.fullname" . }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullname }}-trigger-secret
  labels:
    {{- include "loki-docs.labels" . | nindent 4 }}
stringData:
  WebHookSecretKey: {{ .Values.source.triggerSecret | quote }}

